### ISSUE TITLE
_wait_for_msg() on CPython with TLS connection raises ssl.SSLWantReadError on timeout

### ISSUE THREAD

**Issue by vladak** [adafruit/Adafruit_CircuitPython_MiniMQTT#154]
When connected via TLS, i.e. the socket is wrapped using the `ssl_context` and there is nothing to be read in the loop, it results in:
```
Traceback (most recent call last):
  File "c.py", line 132, in <module>
    mqtt_client.loop()
  File "/Users/vladimirkotal/Pi/Adafruit_CircuitPython_MiniMQTT/adafruit_minimqtt/adafruit_minimqtt.py", line 955, in loop
    rc = self._wait_for_msg(timeout)
  File "/Users/vladimirkotal/Pi/Adafruit_CircuitPython_MiniMQTT/adafruit_minimqtt/adafruit_minimqtt.py", line 976, in _wait_for_msg
    res = self._sock_exact_recv(1)
  File "/Users/vladimirkotal/Pi/Adafruit_CircuitPython_MiniMQTT/adafruit_minimqtt/adafruit_minimqtt.py", line 1077, in _sock_exact_recv
    recv_len = self._sock.recv_into(rc, bufsize)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2633)
```

In such case, `_wait_for_msg()` should return `None`, however the ssl exception fires through: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/342b8c99b2c8f10b605cc8311bf5f394f4d18e92/adafruit_minimqtt/adafruit_minimqtt.py#L967-L972

Note that the line numbers do not match because I am using minimqtt code for one of my PRs, however that should not matter.

Trouble is that the `ssl.SSLWantReadError` does not seem to be reachable from the ssl context passed to `MQTT()` init function. The exception class is based on `OSError`, however catching that would be too generic, I think.

**Comment by vladak** [comment]
Trying to reproduce this with 8.0.0-beta.6 and adafruit_minimqtt==7.3.2 on QtPy with this code:
```python
import json
import ssl
import time
import traceback

import adafruit_logging as logging
import adafruit_minimqtt.adafruit_minimqtt as MQTT
import board
import microcontroller
import neopixel
import socketpool
import supervisor
import wifi

from logutil import get_log_level

try:
    from secrets import secrets
except ImportError:
    print(
        "WiFi and Adafruit IO credentials are kept in secrets.py, please add them there!"
    )
    raise


# pylint: disable=unused-argument, redefined-outer-name, invalid-name
def connect(mqtt_client, userdata, flags, rc):
    """
    This function will be called when the mqtt_client is connected
    successfully to the broker.
    """
    logger = logging.getLogger(__name__)

    logger.info("Connected to MQTT Broker!")
    logger.debug(f"Flags: {flags}\n RC: {rc}")


# pylint: disable=unused-argument, invalid-name
def disconnect(mqtt_client, userdata, rc):
    """
    This method is called when the mqtt_client disconnects from the broker.
    """
    logger = logging.getLogger(__name__)

    logger.info("Disconnected from MQTT Broker!")


def publish(mqtt_client, userdata, topic, pid):
    """
    This method is called when the mqtt_client publishes data to a feed.
    """
    logger = logging.getLogger(__name__)

    logger.info(f"Published to {topic} with PID {pid}")


def blink(pixel):
    """
    Blink the Neo pixel blue.
    """
    pixel.brightness = 0.3
    pixel.fill((0, 0, 255))
    time.sleep(0.5)
    pixel.brightness = 0


def main():
    pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)

    log_level = get_log_level(secrets["log_level"])
    logger = logging.getLogger(__name__)
    logger.setLevel(log_level)

    logger.info("Running")

    # Connect to Wi-Fi
    logger.info("Connecting to wifi")
    wifi.radio.connect(secrets["ssid"], secrets["password"], timeout=10)
    logger.info(f"Connected to {secrets['ssid']}")
    logger.debug(f"IP: {wifi.radio.ipv4_address}")
    logger.debug(f"MAC: {wifi.radio.mac_address}")

    # Create a socket pool
    pool = socketpool.SocketPool(wifi.radio)

    ssl_context = ssl.create_default_context()
    cadata = """
-----BEGIN CERTIFICATE-----
MIIEAzCCAuugAwIBAgIUBY1hlCGvdj4NhBXkZ/uLUZNILAwwDQYJKoZIhvcNAQEL
BQAwgZAxCzAJBgNVBAYTAkdCMRcwFQYDVQQIDA5Vbml0ZWQgS2luZ2RvbTEOMAwG
A1UEBwwFRGVyYnkxEjAQBgNVBAoMCU1vc3F1aXR0bzELMAkGA1UECwwCQ0ExFjAU
BgNVBAMMDW1vc3F1aXR0by5vcmcxHzAdBgkqhkiG9w0BCQEWEHJvZ2VyQGF0Y2hv
by5vcmcwHhcNMjAwNjA5MTEwNjM5WhcNMzAwNjA3MTEwNjM5WjCBkDELMAkGA1UE
BhMCR0IxFzAVBgNVBAgMDlVuaXRlZCBLaW5nZG9tMQ4wDAYDVQQHDAVEZXJieTES
MBAGA1UECgwJTW9zcXVpdHRvMQswCQYDVQQLDAJDQTEWMBQGA1UEAwwNbW9zcXVp
dHRvLm9yZzEfMB0GCSqGSIb3DQEJARYQcm9nZXJAYXRjaG9vLm9yZzCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAME0HKmIzfTOwkKLT3THHe+ObdizamPg
UZmD64Tf3zJdNeYGYn4CEXbyP6fy3tWc8S2boW6dzrH8SdFf9uo320GJA9B7U1FW
Te3xda/Lm3JFfaHjkWw7jBwcauQZjpGINHapHRlpiCZsquAthOgxW9SgDgYlGzEA
s06pkEFiMw+qDfLo/sxFKB6vQlFekMeCymjLCbNwPJyqyhFmPWwio/PDMruBTzPH
3cioBnrJWKXc3OjXdLGFJOfj7pP0j/dr2LH72eSvv3PQQFl90CZPFhrCUcRHSSxo
E6yjGOdnz7f6PveLIB574kQORwt8ePn0yidrTC1ictikED3nHYhMUOUCAwEAAaNT
MFEwHQYDVR0OBBYEFPVV6xBUFPiGKDyo5V3+Hbh4N9YSMB8GA1UdIwQYMBaAFPVV
6xBUFPiGKDyo5V3+Hbh4N9YSMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
BQADggEBAGa9kS21N70ThM6/Hj9D7mbVxKLBjVWe2TPsGfbl3rEDfZ+OKRZ2j6AC
6r7jb4TZO3dzF2p6dgbrlU71Y/4K0TdzIjRj3cQ3KSm41JvUQ0hZ/c04iGDg/xWf
+pp58nfPAYwuerruPNWmlStWAXf0UTqRtg4hQDWBuUFDJTuWuuBvEXudz74eh/wK
sMwfu1HFvjy5Z0iMDU8PUDepjVolOCue9ashlS4EB5IECdSR2TItnAIiIwimx839
LdUdRudafMu5T5Xma182OC0/u/xRlEm+tvKGGmfFcN0piqVl8OrSPBgIlb+1IKJE
m/XriWr/Cq4h/JfB7NTsezVslgkBaoU=
-----END CERTIFICATE-----
    """
    ssl_context.load_verify_locations(cadata=cadata)

    broker_port = secrets["broker_port"]

    # Set up a MiniMQTT Client
    mqtt_client = MQTT.MQTT(
        broker=secrets["broker"],
        port=broker_port,
        socket_pool=pool,
        ssl_context=ssl_context,
        is_ssl=True,
    )

    mqtt_client.enable_logger(logging, log_level=logging.INFO)

    # Connect callback handlers to mqtt_client
    mqtt_client.on_connect = connect
    mqtt_client.on_disconnect = disconnect
    mqtt_client.on_publish = publish

    logger.info(f"Attempting to connect to MQTT broker {mqtt_client.broker} on port {broker_port}")
    mqtt_client.connect()

    mqtt_topic = secrets["mqtt_topic"]
    logger.info(f"Subscribing to {mqtt_topic}")
    mqtt_client.subscribe(mqtt_topic)

    # data = {"foo": "bar"}
    SIZE = 1024
    data = {'FRAME': [25.8683] * SIZE,   'C': 24.3511, 'RH': 16.9207}

    #logger.info(f"Publishing to {mqtt_topic}")
    #mqtt_client.publish(mqtt_topic, json.dumps(data))

    logger.info("Entering loop")
    while True:
        mqtt_client.loop(timeout=3)
        blink(pixel)
	logger.info("Out from loop()")

    logger.info(f"Disconnecting from MQTT broker")
    mqtt_client.disconnect()


try:
    main()
# pylint: disable=broad-except
except Exception as e:
    # This assumes that such exceptions are quite rare.
    # Otherwise this would drain the battery quickly.
    print("Code stopped by unhandled exception:")
    print(traceback.format_exception(None, e, e.__traceback__))
    RELOAD_TIME = 10
    print(f"Performing a supervisor reload in {RELOAD_TIME} seconds")
    time.sleep(RELOAD_TIME)
    supervisor.reload()
```

It does not lead to the exception even though there are no messages received:
```
1212.091: INFO - Attempting to connect to MQTT broker test.mosquitto.org on port 8883
1212.095: INFO - Establishing a SECURE SSL connection to test.mosquitto.org:8883
1212.906: INFO - Connected to MQTT Broker!
1212.911: INFO - Subscribing to devices/TBD/qtpy
1213.447: INFO - Entering loop
1216.451: INFO - Out from loop()
1219.453: INFO - Out from loop()
1222.456: INFO - Out from loop()
1225.458: INFO - Out from loop()
...
```
which I am not sure is good news or not considering I did not upgrade to 8.1.0.

**Comment by vladak** [comment]
Actually, looking at the stack trace, this is a problem that seems to happen only with CPython.

**Comment by brentru** [comment]
@vladak  
1) Could you clarify - are you expecting messages to be received? The REPL shows you exit from the loop() ("out from loop?"). 
2) The issue title lists "CPython". Are you interested in re-testing that? If not, it's ok, I will.

**Comment by brentru** [comment]
@vladak btw - Thank you for your work, PRs, and issues reported on this library. 

I've had different priorities since writing it (mostly working on Adafruit WipperSnapper). I am getting back to resolving issues with MiniMQTT and enhancing it starting next week.

**Comment by vladak** [comment]
>     1. Could you clarify - are you expecting messages to be received? The REPL shows you exit from the loop() ("out from loop?").

The "Out from loop()" message simply means that the `mqtt_client.loop(timeout=3)` returned, so next iteration of the cycle will be done. See the code above.

For this case, I am not expecting any messages to be received withing the `loop()` (besides `PINGRESP` behind the scenes).
 
>     2. The issue title lists "CPython". Are you interested in re-testing that? If not, it's ok, I will.

I've just tried that, still hitting the same issue.

**Comment by vladak** [comment]
> btw - Thank you for your work, PRs, and issues reported on this library.

You are certainly welcome, I had fun doing that.

> I've had different priorities since writing it (mostly working on Adafruit WipperSnapper). I am getting back to resolving issues with MiniMQTT and enhancing it starting next week.

Cool !
