### ISSUE TITLE
MMQTTException: invalid message received as response to SUBSCRIBE: 0x31 - v7.3.2 and 7.4.0

### ISSUE THREAD

**Issue by cn-schuh** [adafruit/Adafruit_CircuitPython_MiniMQTT#171]
Hello, 

Recently i figured out an probelm after updateing to minimqtt 7.4.0 (same with 7.3.2). When sending multiple subscribes (as str) the error below occurs. Using a list it is even better, but only when send all topics in a single list. 
Problem with the list, i am expecting problems when i am using this in my original code (40 subscribes). It seems to be not related on the retain flag.

Error Message:
Connected to MQTT Broker!
Subscribed to /groups/device with QOS level 0
New message on topic /groups/device: 0
Traceback (most recent call last):
  File "code.py", line 107, in <module>
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 858, in subscribe
MMQTTException: invalid message received as response to SUBSCRIBE: 0x31

Attached a modified code form the example.

To test, the ssid and key has to be added in wifi.radio.connect("", "") in line 21 and broker in line 76. As mentioned, the first occurancy was with 7.3.2. Older versions seems to be fine. 

I hope i didn't missed any new functions and reported these as error.

[code.txt](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/files/12001407/code.txt)

**Comment by cn-schuh** [comment]
Looks like a timing issue, to many subscribes at the same time. Reduced to 4 subscribses, interrupt and next 4.

**Comment by cn-schuh** [comment]
When passing topics by list, it have to be limited to 4 items, break (in my case 0.5), next 4 items and so on.
