### ISSUE TITLE
Rename last_will method -> will_set

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_MiniMQTT#35]
Keeping in-line with Paho-MQTT, we may want to change `last_will` -> `will_set`. It's more descriptive and defines the method better. 

Paho Implementation: `will_set(topic, payload=None, qos=0, retain=False)`

Our Implementation:
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt.py#L192

**Comment by brentru** [comment]
Additionally, LWT should not be called within init since LWT should be set independently prior to connecting.

**Comment by brentru** [comment]
`payload` also needs to be converted into bytes, checking does not occur within `last_will`, causing a failure when attempting to fix.

calling: `client.will_set("devices/{}/status".format(client_id), payload=1, retain=True)`
error:
```
SET LWT
Attempting to connect to SNIP!
Traceback (most recent call last):
  File "code.py", line 94, in <module>
  File "/lib/adafruit_minimqtt.py", line 263, in connect
TypeError: object of type 'int' has no len()
```
