### ISSUE TITLE
Dev Branch Error on Unsubscribe on HA MQTT

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_MiniMQTT#57]
Here's what I got using Home Assistant's MQTT Broker. It had previously done some successful unsubscribes with a response of `bytearray(b'0')`, but here's the info for the crash.
```
New message on topic cmnd/dining-light/POWER: OFF
Unsubscribing from cmnd/dining-light/POWER
Resp:  bytearray(b'\xb0')
Traceback (most recent call last):
  File "code.py", line 127, in <module>
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 862, in loop
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 913, in _wait_for_msg
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 417, in _handle_on_message
  File "code.py", line 89, in message
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 808, in unsubscribe
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 913, in _wait_for_msg
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 417, in _handle_on_message
  File "code.py", line 89, in message
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 815, in unsubscribe
AssertionError: 

Code done running.
```

**Comment by brentru** [comment]
@makermelissa  Could you turn logging on for a more verbose error output? https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py#L98

**Comment by makermelissa** [comment]
Ok, I may have grabbed it from your main branch when I encountered this. I definitely have it running off dev branch now and haven't seen this issue again. If I don't see it anymore, I'll close. If I do, I'll turn on logging.

**Comment by makermelissa** [comment]
Yeah, I'm not seeing this anymore
