### ISSUE TITLE
This lib doesn't seem to work wtih GCP IOT Core 

### ISSUE THREAD

**Issue by geudrik** [adafruit/Adafruit_CircuitPython_MiniMQTT#93]
Original documentation of this issue [here](https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/pull/20#issuecomment-941130355)

On my FeatherS2, this code executes without error on the `Receiving CONNACK packet from broker` line. It, however, hangs indefinitely on the `google_mqtt.connect()` call (second to last line in `main.py`). I also see valid TLS traffic via packet capture on my router - data coming and going. The final print informing of connection success never executes. Ultimately (following the stack left from crtl-C) the hang is [here](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/main/adafruit_minimqtt/adafruit_minimqtt.py#L286)

Enabling logging has also proven difficult as the `adafruit_logging` module doesn't have a `getLogger` method.

Notes: 
- `from arcti.ntp import NTP` comes from [here](https://gitlab.com/-/snippets/2184310)
- `from arcti.logging import Logger` comes from [here](https://gitlab.com/-/snippets/2188558)
- The private key can be generated using the script found in [this tutorial](https://learn.adafruit.com/pyportal-iot-plant-monitor-with-google-cloud-iot-core-and-circuitpython/code-setup#creating-a-rsa-key-pair-3038069-14)
- This is related to two other MR's that I have open [here](https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/pull/20) and [here](https://github.com/adafruit/Adafruit_CircuitPython_RSA/pull/20) (this rabbit hole has gone deep)

```bash
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
main.py output:
2021/10/12 15:31:23 INFO    : Connecting to The Promised LAN
2021/10/12 15:31:26 INFO    : Connected to The Promised LAN
2021/10/12 15:31:26 INFO    : Setting NTP
2021/10/12 15:31:27 INFO    : Generating JWT - this will take a minute... 
2021/10/12 15:31:54 DEBUG   : Your JWT is: eyJ0.....VQ==
2021/10/12 15:31:54 INFO    : Attempting to connect to mqtt.googleapis.com
2021/10/12 15:31:54 DEBUG   : Attempting to establish MQTT connection...
2021/10/12 15:31:54 INFO    : Establishing a SECURE SSL connection to mqtt.googleapis.com:8883
2021/10/12 15:31:56 DEBUG   : Sending CONNECT to broker...
2021/10/12 15:31:56 DEBUG   : Fixed Header: bytearray(b'\x10\xcc\x04\x00')
Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
2021/10/12 15:31:56 DEBUG   : Receiving CONNACK packet from broker
```

```python
# main.py

import json
import socketpool
import wifi
import ssl

from settings import secrets

from arcti.ntp import NTP
from arcti.logging import Logger

from adafruit_gc_iot_core import MQTT_API, Cloud_Core
import adafruit_minimqtt.adafruit_minimqtt as MQTT

logger = Logger()

logger.info(f"Connecting to {secrets['WIFI_SSID']}")
wifi.radio.connect(secrets["WIFI_SSID"], secrets["WIFI_SSID_PASSWORD"])
logger.info(f"Connected to {secrets['WIFI_SSID']}")

logger.info("Setting NTP")
n = NTP()
n.update_rtc()

socketPool = socketpool.SocketPool(wifi.radio)

# Define callback methods which are called when events occur
# pylint: disable=unused-argument, redefined-outer-name
def connect(client, userdata, flags, rc):
    # This function will be called when the client is connected
    # successfully to the broker.
    logger.info('Connected to Google Cloud IoT!')
    logger.debug(f'Flags: {flags}\nRC: {rc}')
    # Subscribes to commands/# topic
    google_mqtt.subscribe_to_all_commands()


def disconnect(client, userdata, rc):
    # This method is called when the client disconnects
    # from the broker.
    logger.warn('Disconnected from Google Cloud IoT!')


def subscribe(client, userdata, topic, granted_qos):
    # This method is called when the client subscribes to a new topic.
    logger.info(f'Subscribed to {topic} with QOS level {granted_qos}')


def unsubscribe(client, userdata, topic, pid):
    # This method is called when the client unsubscribes from a topic.
    logger.info(f'Unsubscribed from {topic} with PID {pid}')


def publish(client, userdata, topic, pid):
    # This method is called when the client publishes data to a topic.
    logger.info(f'Published to {topic} with PID {pid}')


def message(client, topic, msg):
    # This method is called when the client receives data from a topic.
    try:
        # Attempt to decode a JSON command
        msg_dict = json.loads(msg)
        logger.debug(msg_dict)

    except TypeError:
        # Non-JSON command, print normally
        logger.error(f"Message from {topic}: {msg}")


# Initialize Google Cloud IoT Core interface
google_iot = Cloud_Core(secrets={
    "project_id": secrets.get('GCS_PROJECT_ID'),
    "cloud_region": secrets.get('GCS_PROJECT_REGION'),
    "registry_id": secrets.get('GCS_IOT_REGISTRY'),
    "device_id": secrets.get('GCS_IOT_DEVICE'),
    "private_key": secrets.get('GCS_PRIVATE_KEY')
})

# JSON-Web-Token (JWT) Generation
logger.info("Generating JWT - this will take a minute... ")
jwt = google_iot.generate_jwt()
logger.debug(f"Your JWT is: {jwt}")

# Set up a new MiniMQTT Client
client = MQTT.MQTT(broker=google_iot.broker,
                   # username=google_iot.username,
                   username="ItDoesntMatter",
                   password=jwt,
                   client_id=google_iot.cid,
                   socket_pool=socketPool,
                   ssl_context=ssl.create_default_context())

client.enable_logger(logger)

# Initialize Google MQTT API Client
google_mqtt = MQTT_API(client)

# Connect callback handlers to Google MQTT Client
google_mqtt.on_connect = connect
google_mqtt.on_disconnect = disconnect
google_mqtt.on_subscribe = subscribe
google_mqtt.on_unsubscribe = unsubscribe
google_mqtt.on_publish = publish
google_mqtt.on_message = message

logger.info(f'Attempting to connect to {client.broker}')
google_mqtt.connect()
logger.info('Connected to IOT Core! :D')
```

```python
# Pertinent settings.py values
# GCS Creds
    "GCS_PROJECT_ID": " project-id",
    "GCS_PROJECT_REGION": "us-east1",
    "GCS_IOT_REGISTRY": "registry_name",
    "GCS_IOT_DEVICE": "iot_core_device_name",
    "GCS_PRIVATE_KEY": (...)
```

The ctrl-c stack leaves us here
```bash
2021/10/13 21:48:04 DEBUG   : _sock_exact_recv bufsize = 1
Traceback (most recent call last):
  File "main.py", line 107, in <module>
  File "/lib/adafruit_gc_iot_core.py", line 131, in connect
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 505, in connect
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 802, in _wait_for_msg
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 890, in _sock_exact_recv
KeyboardInterrupt: 
```

**Comment by geudrik** [comment]
Further debugging leaves us [here](https://github.com/adafruit/Adafruit_CircuitPython_RSA/pull/20) - this loop is never broken out of, because `op` never is anything other than `None`. I know squat about the MQTT protocol :(

**Comment by geudrik** [comment]
Further backtracing leads me to [here](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/main/adafruit_minimqtt/adafruit_minimqtt.py#L805), which seems to be to indicate that this is a recv timout issue maybe? I have no idea how to resolve this, since `self._sock.recv()`, which I believe is a socket instance, doesn't seem to have documenation around the `recv()` function

**Comment by vladak** [comment]
> Further debugging leaves us [here](https://github.com/adafruit/Adafruit_CircuitPython_RSA/pull/20) - this loop is never broken out of, because `op` never is anything other than `None`. I know squat about the MQTT protocol :(

The MQTT protocol is actually simple and was designed with significant degree of simplicity in mind, I believe. If one avoids stuff like message persistence (retain) and QoS, the spec (https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html) is quite easy to follow.

**Comment by vladak** [comment]
The Google Cloud IoT Core will be [shutdown](https://killedbygoogle.com/) in August 2023, which includes their MQTT bridge, so it is probably not worth pursing this issue further.
